/* data.js — AI BAYAN GRAMMAR 4gr (15 units × 5 ex × 10 items) */
(function () {
  const U = (n, topic, ruleEn, ruleRu, exBuilders) => ({
    id: `u${n}`,
    title: `Unit ${n}`,
    topic,
    ruleEn,
    ruleRu,
    exercises: exBuilders.map((fn, i) => ({
      id: `ex${i + 1}`,
      title: `Exercise ${i + 1}`,
      items: fn(n, i + 1),
    })),
  });

  const item = (id, prompt, answer) => ({ id, prompt, answer, kind: "text" });

  // Templates (same structure for all units)
  function ex_fill(unit, ex, pairs) {
    return pairs.map((p, idx) => item(`u${unit}e${ex}q${idx + 1}`, p[0], p[1]));
  }

  // ---------- UNIT CONTENT ----------
  const units = [];

  // Unit 1 already done earlier (you can keep your Unit 1). Here is a solid full Unit 1:
  units.push(
    U(
      1,
      "Present Simple vs Present Continuous",
      "Present Simple: habits/facts. Present Continuous: action now/temporary. Use do/does for questions in Present Simple; am/is/are for Present Continuous.",
      "Present Simple: привычки/факты. Present Continuous: сейчас/временно. Вопросы: Do/Does (PS) и Am/Is/Are (PC).",
      [
        () =>
          ex_fill(1, 1, [
            ["He ____ (play) football every day.", "plays"],
            ["I ____ (go) to school on Mondays.", "go"],
            ["She ____ (watch) TV now.", "is watching"],
            ["They ____ (do) homework at the moment.", "are doing"],
            ["We ____ (not / like) milk.", "don't like"],
            ["He ____ (not / go) to bed late.", "doesn't go"],
            ["I ____ (read) a book now.", "am reading"],
            ["My dad ____ (work) in a bank.", "works"],
            ["You ____ (listen) to music now.", "are listening"],
            ["Cats ____ (sleep) a lot.", "sleep"],
          ]),
        () =>
          ex_fill(1, 2, [
            ["He ____ to school every day. (go / goes)", "goes"],
            ["They ____ TV now. (watch / are watching)", "are watching"],
            ["I ____ my teeth every morning. (brush / am brushing)", "brush"],
            ["She ____ a sandwich at the moment. (eats / is eating)", "is eating"],
            ["We ____ English on Tuesdays. (have / are having)", "have"],
            ["Listen! The baby ____. (cries / is crying)", "is crying"],
            ["My brother ____ in the yard now. (plays / is playing)", "is playing"],
            ["My mum ____ coffee every day. (drinks / is drinking)", "drinks"],
            ["Right now we ____ a test. (write / are writing)", "are writing"],
            ["It ____ often in autumn. (rains / is raining)", "rains"],
          ]),
        () =>
          ex_fill(1, 3, [
            ["Make a question: (you / like / pizza?)", "do you like pizza?"],
            ["(he / play / football?)", "does he play football?"],
            ["(she / watch / TV now?)", "is she watching tv now?"],
            ["(they / do / homework now?)", "are they doing homework now?"],
            ["(your dad / work / in a bank?)", "does your dad work in a bank?"],
            ["(you / listen / to music now?)", "are you listening to music now?"],
            ["(she / go / to school every day?)", "does she go to school every day?"],
            ["(I / read / now?)", "am i reading now?"],
            ["(they / play / tennis on Sundays?)", "do they play tennis on sundays?"],
            ["(he / sleep / now?)", "is he sleeping now?"],
          ]),
        () =>
          ex_fill(1, 4, [
            ["Make negative: I like apples.", "i don't like apples."],
            ["She plays tennis.", "she doesn't play tennis."],
            ["They are watching TV now.", "they aren't watching tv now."],
            ["He is reading now.", "he isn't reading now."],
            ["We go to school on Mondays.", "we don't go to school on mondays."],
            ["The cat is sleeping now.", "the cat isn't sleeping now."],
            ["My mum drinks tea every day.", "my mum doesn't drink tea every day."],
            ["I am doing homework now.", "i am not doing homework now."],
            ["He goes to bed late.", "he doesn't go to bed late."],
            ["We are having lunch now.", "we aren't having lunch now."],
          ]),
        () =>
          ex_fill(1, 5, [
            ["Translate (RU→EN): Я играю в футбол каждый день.", "i play football every day."],
            ["Он ходит в школу каждый день.", "he goes to school every day."],
            ["Сейчас она читает книгу.", "she is reading a book now."],
            ["Они сейчас делают домашнее задание.", "they are doing homework now."],
            ["Я не люблю молоко.", "i don't like milk."],
            ["Он не играет в теннис.", "he doesn't play tennis."],
            ["Ты сейчас слушаешь музыку?", "are you listening to music now?"],
            ["Она ходит в парк по воскресеньям.", "she goes to the park on sundays."],
            ["Мы сейчас не смотрим телевизор.", "we aren't watching tv now."],
            ["Ты любишь пиццу?", "do you like pizza?"],
          ]),
      ]
    )
  );

  // Unit 2
  units.push(
    U(
      2,
      "Past Simple (regular verbs + be)",
      "Past Simple: finished actions. Regular verbs: V+ed. Be: was/were. Negative: didn't + V1 / wasn't/weren't. Questions: Did…? / Was…?",
      "Past Simple: завершённые действия. Правильные: +ed. be: was/were. Отриц.: didn't / wasn't. Вопрос: Did…? / Was…?",
      [
        () =>
          ex_fill(2, 1, [
            ["Yesterday I ____ (play) football.", "played"],
            ["She ____ (watch) TV last night.", "watched"],
            ["We ____ (visit) our grandparents.", "visited"],
            ["They ____ (clean) the room.", "cleaned"],
            ["He ____ (help) his mum.", "helped"],
            ["I ____ (finish) my homework.", "finished"],
            ["She ____ (open) the window.", "opened"],
            ["We ____ (listen) to music.", "listened"],
            ["They ____ (walk) to school.", "walked"],
            ["He ____ (wash) his hands.", "washed"],
          ]),
        () =>
          ex_fill(2, 2, [
            ["I ____ at home yesterday. (was / were)", "was"],
            ["They ____ happy last weekend. (was / were)", "were"],
            ["She ____ tired yesterday. (was / were)", "was"],
            ["We ____ at school yesterday. (was / were)", "were"],
            ["He ____ late yesterday. (was / were)", "was"],
            ["I ____ ill last week. (was / were)", "was"],
            ["The children ____ noisy. (was / were)", "were"],
            ["My mum ____ busy yesterday. (was / were)", "was"],
            ["We ____ ready. (was / were)", "were"],
            ["The weather ____ nice. (was / were)", "was"],
          ]),
        () =>
          ex_fill(2, 3, [
            ["Make a question: (you / play / football?)", "did you play football?"],
            ["(she / watch / tv?)", "did she watch tv?"],
            ["(they / visit / grandma?)", "did they visit grandma?"],
            ["(he / clean / the room?)", "did he clean the room?"],
            ["(you / help / your mum?)", "did you help your mum?"],
            ["(she / open / the door?)", "did she open the door?"],
            ["(they / walk / to school?)", "did they walk to school?"],
            ["(he / wash / his hands?)", "did he wash his hands?"],
            ["(you / finish / homework?)", "did you finish homework?"],
            ["(she / listen / to music?)", "did she listen to music?"],
          ]),
        () =>
          ex_fill(2, 4, [
            ["Make negative: I played football.", "i didn't play football."],
            ["She watched TV.", "she didn't watch tv."],
            ["They visited grandma.", "they didn't visit grandma."],
            ["He cleaned the room.", "he didn't clean the room."],
            ["We helped our mum.", "we didn't help our mum."],
            ["She opened the door.", "she didn't open the door."],
            ["They walked to school.", "they didn't walk to school."],
            ["He washed his hands.", "he didn't wash his hands."],
            ["I finished homework.", "i didn't finish homework."],
            ["We listened to music.", "we didn't listen to music."],
          ]),
        () =>
          ex_fill(2, 5, [
            ["Translate: Вчера я играл в футбол.", "yesterday i played football."],
            ["Она смотрела телевизор.", "she watched tv."],
            ["Мы были дома.", "we were at home."],
            ["Он был уставший.", "he was tired."],
            ["Они не играли в игры.", "they didn't play games."],
            ["Я не был в школе.", "i wasn't at school."],
            ["Мы не смотрели телевизор.", "we didn't watch tv."],
            ["Она была счастлива.", "she was happy."],
            ["Они были в парке.", "they were in the park."],
            ["Ты играл вчера?", "did you play yesterday?"],
          ]),
      ]
    )
  );

  // Unit 3 (irregular)
  units.push(
    U(
      3,
      "Past Simple (irregular verbs)",
      "Irregular verbs use V2 (go→went). Negative/questions: didn't + V1; Did + subject + V1?",
      "Неправильные глаголы: V2 (go→went). Отриц/вопрос: didn't + V1; Did + подл. + V1?",
      [
        () =>
          ex_fill(3, 1, [
            ["Yesterday I ____ (go) to school.", "went"],
            ["She ____ (see) a cat.", "saw"],
            ["We ____ (eat) pizza.", "ate"],
            ["He ____ (take) a book.", "took"],
            ["They ____ (come) home late.", "came"],
            ["I ____ (drink) juice.", "drank"],
            ["She ____ (find) her bag.", "found"],
            ["We ____ (give) him a gift.", "gave"],
            ["He ____ (get) up early.", "got"],
            ["They ____ (run) fast.", "ran"],
          ]),
        () =>
          ex_fill(3, 2, [
            ["go → (went / goed)", "went"],
            ["see → (saw / seed)", "saw"],
            ["eat → (ate / eated)", "ate"],
            ["come → (came / comed)", "came"],
            ["take → (took / taked)", "took"],
            ["drink → (drank / drinked)", "drank"],
            ["get → (got / geted)", "got"],
            ["run → (ran / runned)", "ran"],
            ["give → (gave / gived)", "gave"],
            ["find → (found / finded)", "found"],
          ]),
        () =>
          ex_fill(3, 3, [
            ["(you / go / home?)", "did you go home?"],
            ["(she / see / the dog?)", "did she see the dog?"],
            ["(they / eat / lunch?)", "did they eat lunch?"],
            ["(he / take / my pen?)", "did he take my pen?"],
            ["(you / drink / milk?)", "did you drink milk?"],
            ["(we / come / early?)", "did we come early?"],
            ["(she / get / a gift?)", "did she get a gift?"],
            ["(they / run / fast?)", "did they run fast?"],
            ["(he / find / the key?)", "did he find the key?"],
            ["(you / give / him a book?)", "did you give him a book?"],
          ]),
        () =>
          ex_fill(3, 4, [
            ["I went home.", "i didn't go home."],
            ["She saw a dog.", "she didn't see a dog."],
            ["We ate pizza.", "we didn't eat pizza."],
            ["He took my pen.", "he didn't take my pen."],
            ["They came late.", "they didn't come late."],
            ["I drank juice.", "i didn't drink juice."],
            ["She found the key.", "she didn't find the key."],
            ["We gave him a gift.", "we didn't give him a gift."],
            ["He got up early.", "he didn't get up early."],
            ["They ran fast.", "they didn't run fast."],
          ]),
        () =>
          ex_fill(3, 5, [
            ["Я пошёл домой.", "i went home."],
            ["Она увидела собаку.", "she saw a dog."],
            ["Мы поели пиццу.", "we ate pizza."],
            ["Он взял мою ручку.", "he took my pen."],
            ["Они пришли рано.", "they came early."],
            ["Я выпил сок.", "i drank juice."],
            ["Она нашла ключ.", "she found the key."],
            ["Мы дали ему подарок.", "we gave him a gift."],
            ["Он встал рано.", "he got up early."],
            ["Они быстро бежали.", "they ran fast."],
          ]),
      ]
    )
  );

  // Unit 4,5,6 already provided by me earlier, but here they are complete in same format:
  // (Short rules to avoid huge text; exercises/answers real.)
  units.push(
    U(
      4,
      "Possessive pronouns + ’s",
      "Possessive pronouns: mine, yours, his, hers, ours, theirs. Possessive ’s shows ownership.",
      "Притяжательные местоимения: mine, yours, his, hers, ours, theirs. ’s — принадлежность.",
      [
        () =>
          ex_fill(4, 1, [
            ["This is my pen. This pen is ____.", "mine"],
            ["That is your bag. That bag is ____.", "yours"],
            ["This is his bike. This bike is ____.", "his"],
            ["That is her hat. That hat is ____.", "hers"],
            ["This is our house. This house is ____.", "ours"],
            ["Those are their books. Those books are ____.", "theirs"],
            ["This is my phone. It’s ____.", "mine"],
            ["That seat is ____. (yours)", "yours"],
            ["This dress is ____. (hers)", "hers"],
            ["These toys are ____. (ours)", "ours"],
          ]),
        () =>
          ex_fill(4, 2, [
            ["(my / mine) is on the table.", "mine"],
            ["This is (her / hers) bag.", "her"],
            ["That pencil is (yours / your).", "yours"],
            ["This is (their / theirs) car.", "their"],
            ["The red ball is (ours / our).", "ours"],
            ["It is (his / he) jacket.", "his"],
            ["This is (my / mine) book.", "my"],
            ["That dog is (theirs / their).", "theirs"],
            ["This is (your / yours) coat.", "your"],
            ["The blue shoes are (hers / her).", "hers"],
          ]),
        () =>
          ex_fill(4, 3, [
            ["Write with ’s: the bag of Tom", "tom's bag"],
            ["the bike of Sara", "sara's bike"],
            ["the book of my dad", "my dad's book"],
            ["the toys of the children", "the children's toys"],
            ["the room of the girls", "the girls' room"],
            ["Make: This is my bag. (mine)", "this is my bag. it's mine."],
            ["That is your pen. (yours)", "that is your pen. it's yours."],
            ["This is her hat. (hers)", "this is her hat. it's hers."],
            ["Those are their books. (theirs)", "those are their books. they're theirs."],
            ["This is our house. (ours)", "this is our house. it's ours."],
          ]),
        () =>
          ex_fill(4, 4, [
            ["Fix: This bag is my.", "this bag is mine."],
            ["Fix: That pen is your.", "that pen is yours."],
            ["Fix: This hat is her.", "this hat is hers."],
            ["Fix: Those books are their.", "those books are theirs."],
            ["Fix: This house is our.", "this house is ours."],
            ["Make negative: This is my phone. (mine)", "this isn't my phone. it isn't mine."],
            ["That is your seat. (yours)", "that isn't your seat. it isn't yours."],
            ["This is her dress. (hers)", "this isn't her dress. it isn't hers."],
            ["Those are our toys. (ours)", "those aren't our toys. they aren't ours."],
            ["Those are their books. (theirs)", "those aren't their books. they aren't theirs."],
          ]),
        () =>
          ex_fill(4, 5, [
            ["Это моя ручка. Она моя.", "this is my pen. it's mine."],
            ["Это твоя сумка. Она твоя.", "this is your bag. it's yours."],
            ["Это её шапка. Она её.", "this is her hat. it's hers."],
            ["Это его велосипед. Он его.", "this is his bike. it's his."],
            ["Это наш дом. Он наш.", "this is our house. it's ours."],
            ["Это их книги. Они их.", "these are their books. they're theirs."],
            ["Сумка Тома.", "tom's bag"],
            ["Книга моей мамы.", "my mum's book"],
            ["Комната девочек.", "the girls' room"],
            ["Игрушки детей.", "the children's toys"],
          ]),
      ]
    )
  );

  units.push(
    U(
      5,
      "Have to / must + Why/Because",
      "have to/has to = obligation. don't have to = no need. mustn't = forbidden. Why? Because…",
      "have to/has to = обязанность. don't have to = не нужно. mustn't = нельзя. Why? Because…",
      [
        () =>
          ex_fill(5, 1, [
            ["I ____ to do my homework. (have/has)", "have"],
            ["He ____ to wear a uniform. (have/has)", "has"],
            ["We ____ to get up early. (have/has)", "have"],
            ["She ____ to help her mum. (have/has)", "has"],
            ["They ____ to be quiet. (have/has)", "have"],
            ["My dad ____ to go to work. (have/has)", "has"],
            ["I ____ to clean my room today.", "have"],
            ["My sister ____ to study for the test.", "has"],
            ["We ____ to be on time.", "have"],
            ["He ____ to brush his teeth.", "has"],
          ]),
        () =>
          ex_fill(5, 2, [
            ["You (must / mustn't) stop at a red light.", "must"],
            ["You (mustn't / don't have to) run in the corridor.", "mustn't"],
            ["We (don't have to / mustn't) wear a uniform today.", "don't have to"],
            ["You (must / don't have to) do your homework.", "must"],
            ["You (mustn't / don't have to) eat sweets before dinner.", "mustn't"],
            ["I (must / don't have to) buy bread today.", "must"],
            ["She (mustn't / doesn't have to) go today.", "doesn't have to"],
            ["You (must / mustn't) be polite.", "must"],
            ["We (mustn't / don't have to) shout in class.", "mustn't"],
            ["He (must / doesn't have to) study now.", "must"],
          ]),
        () =>
          ex_fill(5, 3, [
            ["(you / have to / wear a uniform?)", "do you have to wear a uniform?"],
            ["(he / have to / get up early?)", "does he have to get up early?"],
            ["(we / have to / clean the room?)", "do we have to clean the room?"],
            ["(she / have to / help her mum?)", "does she have to help her mum?"],
            ["(they / have to / be quiet?)", "do they have to be quiet?"],
            ["Make: Why? Because: (I study / I want good marks)", "why do you study? because i want good marks."],
            ["(He is late / the bus was late)", "why is he late? because the bus was late."],
            ["(We stay at home / it is raining)", "why do we stay at home? because it is raining."],
            ["(She is happy / it is her birthday)", "why is she happy? because it is her birthday."],
            ["(They run / they are late)", "why do they run? because they are late."],
          ]),
        () =>
          ex_fill(5, 4, [
            ["I have to do homework.", "i don't have to do homework."],
            ["He has to get up early.", "he doesn't have to get up early."],
            ["We have to wear a uniform.", "we don't have to wear a uniform."],
            ["She has to help her mum.", "she doesn't have to help her mum."],
            ["They have to be quiet.", "they don't have to be quiet."],
            ["Make mustn’t: You can run here.", "you mustn't run here."],
            ["You can shout in class.", "you mustn't shout in class."],
            ["You can eat in the library.", "you mustn't eat in the library."],
            ["You can be rude.", "you mustn't be rude."],
            ["You can play with matches.", "you mustn't play with matches."],
          ]),
        () =>
          ex_fill(5, 5, [
            ["Мне нужно сделать домашнее задание.", "i have to do my homework."],
            ["Ему нужно встать рано.", "he has to get up early."],
            ["Нам не нужно идти сегодня.", "we don't have to go today."],
            ["Тебе нельзя бегать здесь.", "you mustn't run here."],
            ["Почему ты учишься? Потому что хочу хорошие оценки.", "why do you study? because i want good marks."],
            ["Ей нужно помочь маме.", "she has to help her mum."],
            ["Им нельзя шуметь в классе.", "they mustn't be noisy in class."],
            ["Тебе нужно быть вежливым.", "you must be polite."],
            ["Почему он опоздал? Потому что автобус был поздно.", "why was he late? because the bus was late."],
            ["Нам нужно быть вовремя.", "we have to be on time."],
          ]),
      ]
    )
  );

  units.push(
    U(
      6,
      "Comparatives & Superlatives",
      "Comparative: -er / more. Superlative: the -est / the most. Irregular: good→better→best, bad→worse→worst.",
      "Сравнительная: -er / more. Превосходная: the -est / the most. Искл.: good→better→best, bad→worse→worst.",
      [
        () =>
          ex_fill(6, 1, [
            ["small → ____", "smaller"],
            ["tall → ____", "taller"],
            ["fast → ____", "faster"],
            ["big → ____", "bigger"],
            ["happy → ____", "happier"],
            ["nice → ____", "nicer"],
            ["hot → ____", "hotter"],
            ["cold → ____", "colder"],
            ["good → ____", "better"],
            ["bad → ____", "worse"],
          ]),
        () =>
          ex_fill(6, 2, [
            ["This book is (more interesting / interestinger).", "more interesting"],
            ["A car is (faster / fast).", "faster"],
            ["My bag is (bigger / biger).", "bigger"],
            ["She is (happier / happyer) today.", "happier"],
            ["This test is (easier / more easy).", "easier"],
            ["He is (better / gooder) at maths.", "better"],
            ["This chair is (more comfortable / comfortabler).", "more comfortable"],
            ["Winter is (colder / coldest) than autumn.", "colder"],
            ["My room is (cleaner / cleanest) today.", "cleaner"],
            ["This film is (worse / badder) than that one.", "worse"],
          ]),
        () =>
          ex_fill(6, 3, [
            ["small →", "the smallest"],
            ["tall →", "the tallest"],
            ["fast →", "the fastest"],
            ["big →", "the biggest"],
            ["happy →", "the happiest"],
            ["nice →", "the nicest"],
            ["good →", "the best"],
            ["bad →", "the worst"],
            ["interesting →", "the most interesting"],
            ["comfortable →", "the most comfortable"],
          ]),
        () =>
          ex_fill(6, 4, [
            ["(Anna / tall / than / Tom)", "anna is taller than tom."],
            ["(This bag / big / than / that bag)", "this bag is bigger than that bag."],
            ["(Winter / cold / than / spring)", "winter is colder than spring."],
            ["(This book / interesting / than / that book)", "this book is more interesting than that book."],
            ["(He / good / at maths / than / me)", "he is better at maths than me."],
            ["(Tom / tall / in class)", "tom is the tallest in the class."],
            ["(This / good / day)", "this is the best day."],
            ["(That film / bad / film)", "that film is the worst film."],
            ["(This / interesting / book)", "this is the most interesting book."],
            ["(This chair / comfortable / chair)", "this is the most comfortable chair."],
          ]),
        () =>
          ex_fill(6, 5, [
            ["Моя сумка больше, чем твоя.", "my bag is bigger than yours."],
            ["Зима холоднее, чем весна.", "winter is colder than spring."],
            ["Анна выше, чем Том.", "anna is taller than tom."],
            ["Этот фильм лучше, чем тот.", "this film is better than that one."],
            ["Это самый лучший день.", "this is the best day."],
            ["Это самая маленькая кошка.", "this is the smallest cat."],
            ["Он самый высокий в классе.", "he is the tallest in the class."],
            ["Это самый худший фильм.", "this is the worst film."],
            ["Эта книга более интересная, чем та.", "this book is more interesting than that book."],
            ["Этот стул самый удобный.", "this chair is the most comfortable."],
          ]),
      ]
    )
  );

  // Units 7–15 (same quality; темы школьные)
  // Чтобы файл не был гигантским в чате, я сгенерировала для них корректные задания + ответы по темам.
  // (Ты получишь весь набор 7–15 ниже — он сразу работает.)
  const auto = (n, topic, en, ru, pack) =>
    units.push(
      U(n, topic, en, ru, [
        () => ex_fill(n, 1, pack.fill),
        () => ex_fill(n, 2, pack.choose),
        () => ex_fill(n, 3, pack.qs),
        () => ex_fill(n, 4, pack.neg),
        () => ex_fill(n, 5, pack.tr),
      ])
    );

  auto(7, "Will / won’t", "will/won't + V1. Questions: Will + subject + V1?", "will/won’t + V1. Вопрос: Will + подл. + V1?", {
    fill: [
      ["I ____ help you tomorrow. (will)", "will"],
      ["She ____ not go today. (won't)", "won't"],
      ["They ____ play later. (will)", "will"],
      ["He ____ not buy it. (won't)", "won't"],
      ["We ____ visit grandma next week. (will)", "will"],
      ["It ____ rain soon. (will)", "will"],
      ["I ____ not be late. (won't)", "won't"],
      ["My dad ____ drive me. (will)", "will"],
      ["She ____ call you. (will)", "will"],
      ["They ____ not shout. (won't)", "won't"],
    ],
    choose: [
      ["Choose: I (will / do) go tomorrow.", "will"],
      ["Choose: She (won't / doesn't) come.", "won't"],
      ["Choose: Will you (play / played)?", "play"],
      ["Choose: He (will / is) help.", "will"],
      ["Choose: They (won't / aren't) be late.", "won't"],
      ["Choose: We (will / were) study.", "will"],
      ["Choose: Will she (buy / buys) it?", "buy"],
      ["Choose: It (will / is) snow.", "will"],
      ["Choose: I (won't / don't) forget.", "won't"],
      ["Choose: Will they (go / went)?", "go"],
    ],
    qs: [
      ["(you / help / me?)", "will you help me?"],
      ["(she / come / tomorrow?)", "will she come tomorrow?"],
      ["(they / play / later?)", "will they play later?"],
      ["(he / be / late?)", "will he be late?"],
      ["(we / visit / grandma?)", "will we visit grandma?"],
      ["(it / rain / soon?)", "will it rain soon?"],
      ["(your dad / drive / you?)", "will your dad drive you?"],
      ["(i / pass / the test?)", "will i pass the test?"],
      ["(she / call / you?)", "will she call you?"],
      ["(they / shout?)", "will they shout?"],
    ],
    neg: [
      ["Make negative: I will go.", "i won't go."],
      ["She will come.", "she won't come."],
      ["They will play.", "they won't play."],
      ["He will help.", "he won't help."],
      ["We will visit grandma.", "we won't visit grandma."],
      ["It will rain.", "it won't rain."],
      ["I will be late.", "i won't be late."],
      ["My dad will drive me.", "my dad won't drive me."],
      ["She will call you.", "she won't call you."],
      ["They will shout.", "they won't shout."],
    ],
    tr: [
      ["Я помогу тебе завтра.", "i will help you tomorrow."],
      ["Она не придёт сегодня.", "she won't come today."],
      ["Они будут играть позже.", "they will play later."],
      ["Он не купит это.", "he won't buy it."],
      ["Мы навестим бабушку на следующей неделе.", "we will visit grandma next week."],
      ["Будет дождь скоро.", "it will rain soon."],
      ["Я не опоздаю.", "i won't be late."],
      ["Папа отвезёт меня.", "my dad will drive me."],
      ["Она позвонит тебе.", "she will call you."],
      ["Они не будут кричать.", "they won't shout."],
    ],
  });

  auto(8, "Much / many / some / any", "many (countable plural), much (uncountable). some in positive, any in questions/negative.", "many — исчисл., much — неисчисл. some — утверд., any — вопрос/отриц.", {
    fill: [
      ["There are ____ apples. (many)", "many"],
      ["There is ____ milk. (much)", "much"],
      ["I have ____ friends. (many)", "many"],
      ["We need ____ water. (much)", "much"],
      ["I have ____ bread. (some)", "some"],
      ["Do you have ____ juice? (any)", "any"],
      ["There isn't ____ cheese. (any)", "any"],
      ["We bought ____ bananas. (some)", "some"],
      ["How ____ books? (many)", "many"],
      ["How ____ money? (much)", "much"],
    ],
    choose: [
      ["Choose: There is (much/many) sugar.", "much"],
      ["Choose: There are (much/many) cars.", "many"],
      ["Choose: I have (some/any) homework. (positive)", "some"],
      ["Choose: Do you have (some/any) pens?", "any"],
      ["Choose: There isn't (some/any) tea.", "any"],
      ["Choose: We need (much/many) time.", "much"],
      ["Choose: How (much/many) students?", "many"],
      ["Choose: How (much/many) water?", "much"],
      ["Choose: I bought (some/any) apples.", "some"],
      ["Choose: Are there (some/any) cookies?", "any"],
    ],
    qs: [
      ["Make a question: (there / any / milk?)", "is there any milk?"],
      ["(you / have / any / friends?)", "do you have any friends?"],
      ["(there / any / apples?)", "are there any apples?"],
      ["(we / need / much / time?)", "do we need much time?"],
      ["(how many / books / there?)", "how many books are there?"],
      ["(how much / water / there?)", "how much water is there?"],
      ["(you / want / any / juice?)", "do you want any juice?"],
      ["(there / any / sugar?)", "is there any sugar?"],
      ["(she / have / any / homework?)", "does she have any homework?"],
      ["(they / have / many / toys?)", "do they have many toys?"],
    ],
    neg: [
      ["Make negative: There is some milk.", "there isn't any milk."],
      ["I have some friends.", "i don't have any friends."],
      ["There are some apples.", "there aren't any apples."],
      ["We need much time.", "we don't need much time."],
      ["She has some homework.", "she doesn't have any homework."],
      ["There is some sugar.", "there isn't any sugar."],
      ["I want some juice.", "i don't want any juice."],
      ["We have many books.", "we don't have many books."],
      ["They have some toys.", "they don't have any toys."],
      ["There is some bread.", "there isn't any bread."],
    ],
    tr: [
      ["У меня много друзей.", "i have many friends."],
      ["В холодильнике много молока.", "there is much milk."],
      ["У тебя есть сок?", "do you have any juice?"],
      ["У нас нет сыра.", "we don't have any cheese."],
      ["Сколько книг там?", "how many books are there?"],
      ["Сколько воды там?", "how much water is there?"],
      ["У меня есть немного хлеба.", "i have some bread."],
      ["Там нет сахара.", "there isn't any sugar."],
      ["Я купила немного бананов.", "i bought some bananas."],
      ["Есть ли там яблоки?", "are there any apples?"],
    ],
  });

  // Units 9–15 (коротко, но все ответы реальные и проверяемые)
  auto(9, "Infinitive of purpose (to + V)", "to + verb shows purpose: I went to the shop to buy bread.", "to + глагол показывает цель.", {
    fill: [
      ["I went to the shop ____ buy bread.", "to"],
      ["She studied ____ get good marks.", "to"],
      ["We use a pencil ____ write.", "to"],
      ["He went outside ____ play.", "to"],
      ["They came here ____ help.", "to"],
      ["I called you ____ ask a question.", "to"],
      ["We went to the park ____ run.", "to"],
      ["She opened the box ____ see inside.", "to"],
      ["He stopped ____ talk to me.", "to"],
      ["They stayed ____ finish the work.", "to"],
    ],
    choose: [
      ["Choose: I went to the shop (to / for) buy bread.", "to"],
      ["Choose: She studied (to / at) get good marks.", "to"],
      ["Choose: We use a pen (to / in) write.", "to"],
      ["Choose: He went outside (to / from) play.", "to"],
      ["Choose: They came (to / into) help.", "to"],
      ["Choose: I called you (to / at) ask.", "to"],
      ["Choose: We went (to / on) the park to run.", "to"],
      ["Choose: She opened it (to / for) see inside.", "to"],
      ["Choose: He stopped (to / for) talk.", "to"],
      ["Choose: They stayed (to / at) finish.", "to"],
    ],
    qs: [
      ["Make a question: (why / you / go / to the shop?)", "why did you go to the shop?"],
      ["(why / she / study?)", "why did she study?"],
      ["(why / you / call / me?)", "why did you call me?"],
      ["(why / they / come here?)", "why did they come here?"],
      ["(why / he / go outside?)", "why did he go outside?"],
      ["(why / we / use a pencil?)", "why do we use a pencil?"],
      ["(why / she / open the box?)", "why did she open the box?"],
      ["(why / they / stay?)", "why did they stay?"],
      ["(why / he / stop?)", "why did he stop?"],
      ["(why / you / go to the park?)", "why did you go to the park?"],
    ],
    neg: [
      ["Make negative: I went to the shop to buy bread.", "i didn't go to the shop to buy bread."],
      ["She studied to get good marks.", "she didn't study to get good marks."],
      ["We use a pencil to write.", "we don't use a pencil to write."],
      ["He went outside to play.", "he didn't go outside to play."],
      ["They came here to help.", "they didn't come here to help."],
      ["I called you to ask a question.", "i didn't call you to ask a question."],
      ["We went to the park to run.", "we didn't go to the park to run."],
      ["She opened the box to see inside.", "she didn't open the box to see inside."],
      ["He stopped to talk to me.", "he didn't stop to talk to me."],
      ["They stayed to finish the work.", "they didn't stay to finish the work."],
    ],
    tr: [
      ["Я пошёл в магазин, чтобы купить хлеб.", "i went to the shop to buy bread."],
      ["Она училась, чтобы получить хорошие оценки.", "she studied to get good marks."],
      ["Мы используем карандаш, чтобы писать.", "we use a pencil to write."],
      ["Он вышел на улицу, чтобы играть.", "he went outside to play."],
      ["Они пришли сюда, чтобы помочь.", "they came here to help."],
      ["Я позвонил тебе, чтобы задать вопрос.", "i called you to ask a question."],
      ["Мы пошли в парк, чтобы бегать.", "we went to the park to run."],
      ["Она открыла коробку, чтобы посмотреть внутрь.", "she opened the box to see inside."],
      ["Он остановился, чтобы поговорить.", "he stopped to talk to me."],
      ["Они остались, чтобы закончить работу.", "they stayed to finish the work."],
    ],
  });

  // 10–15: Present Perfect, ever/never, should/could, object pronouns + who/which, past continuous, PS vs PC
  // (Для краткости не расписываю тут все 600 строк в объяснении — но в данных всё есть.)
  // Я добавляю их готовыми “настоящими” заданиями ниже (полный комплект).

  function addUnit10to15() {
    const add = (n, topic, en, ru, packs) => auto(n, topic, en, ru, packs);

    add(10, "Present Perfect (have/has + V3)", "have/has + V3 for experience/result. Negative: haven't/hasn't. Question: Have/Has…?", "have/has + V3. Отриц.: haven't/hasn't. Вопрос: Have/Has…?", {
      fill: [
        ["I ____ (finish) my homework. (V3)", "have finished"],
        ["She ____ (eat) lunch. (V3)", "has eaten"],
        ["We ____ (see) this film. (V3)", "have seen"],
        ["He ____ (go) home. (V3)", "has gone"],
        ["They ____ (drink) tea. (V3)", "have drunk"],
        ["I ____ (be) to London. (V3)", "have been"],
        ["She ____ (write) a letter. (V3)", "has written"],
        ["We ____ (do) the test. (V3)", "have done"],
        ["He ____ (take) my book. (V3)", "has taken"],
        ["They ____ (clean) the room. (V3)", "have cleaned"],
      ],
      choose: [
        ["Choose: She (have/has) finished.", "has"],
        ["Choose: I (have/has) eaten.", "have"],
        ["Choose: They (have/has) gone.", "have"],
        ["Choose: He (have/has) seen it.", "has"],
        ["Choose: We (have/has) done it.", "have"],
        ["Choose: She (haven't/hasn't) finished.", "hasn't"],
        ["Choose: I (haven't/hasn't) been there.", "haven't"],
        ["Choose: Has/Have he done it?", "has"],
        ["Choose: Has/Have they eaten?", "have"],
        ["Choose: Has/Have you finished?", "have"],
      ],
      qs: [
        ["(you / finish / homework?)", "have you finished homework?"],
        ["(she / eat / lunch?)", "has she eaten lunch?"],
        ["(they / see / this film?)", "have they seen this film?"],
        ["(he / go / home?)", "has he gone home?"],
        ["(we / do / the test?)", "have we done the test?"],
        ["(she / write / a letter?)", "has she written a letter?"],
        ["(you / be / to London?)", "have you been to london?"],
        ["(they / clean / the room?)", "have they cleaned the room?"],
        ["(he / take / my book?)", "has he taken my book?"],
        ["(you / drink / tea?)", "have you drunk tea?"],
      ],
      neg: [
        ["Make negative: I have finished homework.", "i haven't finished homework."],
        ["She has eaten lunch.", "she hasn't eaten lunch."],
        ["They have seen the film.", "they haven't seen the film."],
        ["He has gone home.", "he hasn't gone home."],
        ["We have done the test.", "we haven't done the test."],
        ["She has written a letter.", "she hasn't written a letter."],
        ["I have been to London.", "i haven't been to london."],
        ["They have cleaned the room.", "they haven't cleaned the room."],
        ["He has taken my book.", "he hasn't taken my book."],
        ["We have drunk tea.", "we haven't drunk tea."],
      ],
      tr: [
        ["Я закончил домашнее задание.", "i have finished homework."],
        ["Она уже поела.", "she has eaten lunch."],
        ["Мы видели этот фильм.", "we have seen this film."],
        ["Он ушёл домой.", "he has gone home."],
        ["Они выпили чай.", "they have drunk tea."],
        ["Я был в Лондоне.", "i have been to london."],
        ["Она написала письмо.", "she has written a letter."],
        ["Мы сделали тест.", "we have done the test."],
        ["Он взял мою книгу.", "he has taken my book."],
        ["Они убрали комнату.", "they have cleaned the room."],
      ],
    });

    add(11, "Present Perfect: ever / never", "ever in questions; never in affirmative = 'not at any time'.", "ever — в вопросах; never — 'никогда' в утвердительном.", {
      fill: [
        ["Have you ____ been to London?", "ever"],
        ["I have ____ eaten sushi.", "never"],
        ["Has she ____ ridden a horse?", "ever"],
        ["He has ____ played chess.", "never"],
        ["Have they ____ seen snow?", "ever"],
        ["We have ____ been to China.", "never"],
        ["Has he ____ broken his arm?", "ever"],
        ["I have ____ met a famous person.", "never"],
        ["Have you ____ tried karaoke?", "ever"],
        ["She has ____ forgotten my birthday.", "never"],
      ],
      choose: [
        ["Choose: Have you (ever/never) been to Paris?", "ever"],
        ["Choose: I have (ever/never) been to Paris. (meaning: not)", "never"],
        ["Choose: Has he (ever/never) eaten sushi?", "ever"],
        ["Choose: She has (ever/never) eaten sushi. (meaning: not)", "never"],
        ["Choose: Have they (ever/never) played tennis?", "ever"],
        ["Choose: We have (ever/never) played tennis. (meaning: not)", "never"],
        ["Choose: Has she (ever/never) seen snow?", "ever"],
        ["Choose: He has (ever/never) seen snow. (meaning: not)", "never"],
        ["Choose: Have you (ever/never) tried it?", "ever"],
        ["Choose: I have (ever/never) tried it. (meaning: not)", "never"],
      ],
      qs: [
        ["(you / ever / be / to London?)", "have you ever been to london?"],
        ["(she / ever / ride / a horse?)", "has she ever ridden a horse?"],
        ["(he / ever / play / chess?)", "has he ever played chess?"],
        ["(they / ever / see / snow?)", "have they ever seen snow?"],
        ["(we / ever / try / karaoke?)", "have we ever tried karaoke?"],
        ["(you / ever / eat / sushi?)", "have you ever eaten sushi?"],
        ["(he / ever / break / his arm?)", "has he ever broken his arm?"],
        ["(she / ever / meet / a famous person?)", "has she ever met a famous person?"],
        ["(they / ever / visit / Paris?)", "have they ever visited paris?"],
        ["(you / ever / travel / by plane?)", "have you ever travelled by plane?"],
      ],
      neg: [
        ["Make with never: I haven't been to London.", "i have never been to london."],
        ["She hasn't ridden a horse.", "she has never ridden a horse."],
        ["He hasn't played chess.", "he has never played chess."],
        ["They haven't seen snow.", "they have never seen snow."],
        ["We haven't tried karaoke.", "we have never tried karaoke."],
        ["I haven't eaten sushi.", "i have never eaten sushi."],
        ["He hasn't broken his arm.", "he has never broken his arm."],
        ["She hasn't met a famous person.", "she has never met a famous person."],
        ["They haven't visited Paris.", "they have never visited paris."],
        ["I haven't travelled by plane.", "i have never travelled by plane."],
      ],
      tr: [
        ["Ты когда-нибудь был в Лондоне?", "have you ever been to london?"],
        ["Я никогда не ел суши.", "i have never eaten sushi."],
        ["Она когда-нибудь каталась на лошади?", "has she ever ridden a horse?"],
        ["Он никогда не играл в шахматы.", "he has never played chess."],
        ["Они когда-нибудь видели снег?", "have they ever seen snow?"],
        ["Мы никогда не были в Китае.", "we have never been to china."],
        ["Он когда-нибудь ломал руку?", "has he ever broken his arm?"],
        ["Я никогда не встречал знаменитость.", "i have never met a famous person."],
        ["Ты когда-нибудь пробовал караоке?", "have you ever tried karaoke?"],
        ["Она никогда не забывала мой день рождения.", "she has never forgotten my birthday."],
      ],
    });

    add(12, "Should / shouldn’t + could / couldn’t", "should = advice; could = ability/permission (past/general).", "should — совет; could — мог/умел.", {
      fill: [
        ["You ____ drink water. (advice)", "should"],
        ["You ____ eat too many sweets. (negative advice)", "shouldn't"],
        ["He ____ swim when he was 6. (ability)", "could"],
        ["She ____ read at 5. (ability)", "could"],
        ["I ____ go out yesterday. (couldn't)", "couldn't"],
        ["We ____ be quiet in class. (advice)", "should"],
        ["They ____ run fast. (ability)", "could"],
        ["You ____ be rude. (negative advice)", "shouldn't"],
        ["He ____ play the piano. (ability)", "could"],
        ["She ____ open the door. (couldn't)", "couldn't"],
      ],
      choose: [
        ["Choose: You (should/ could) do homework. (advice)", "should"],
        ["Choose: I (could/ should) ride a bike at 7. (ability)", "could"],
        ["Choose: You (shouldn't/ couldn't) shout in class. (advice)", "shouldn't"],
        ["Choose: He (could/ should) read at 5. (ability)", "could"],
        ["Choose: She (should/ could) see a doctor. (advice)", "should"],
        ["Choose: I (couldn't/ shouldn't) go out yesterday. (ability)", "couldn't"],
        ["Choose: You (shouldn't/ couldn't) eat junk food every day. (advice)", "shouldn't"],
        ["Choose: They (could/ should) swim well. (ability)", "could"],
        ["Choose: He (should/ could) be polite. (advice)", "should"],
        ["Choose: She (couldn't/ shouldn't) open the jar. (ability)", "couldn't"],
      ],
      qs: [
        ["Make a question: (should / i / study?)", "should i study?"],
        ["(should / we / be quiet?)", "should we be quiet?"],
        ["(could / you / swim at 6?)", "could you swim at 6?"],
        ["(could / he / read at 5?)", "could he read at 5?"],
        ["(should / she / see a doctor?)", "should she see a doctor?"],
        ["(could / they / run fast?)", "could they run fast?"],
        ["(should / you / drink water?)", "should you drink water?"],
        ["(could / i / ride a bike at 7?)", "could i ride a bike at 7?"],
        ["(should / he / be polite?)", "should he be polite?"],
        ["(could / she / open the door?)", "could she open the door?"],
      ],
      neg: [
        ["Make negative advice: You should eat sweets.", "you shouldn't eat sweets."],
        ["You should be rude.", "you shouldn't be rude."],
        ["We should shout in class.", "we shouldn't shout in class."],
        ["He should go to bed late.", "he shouldn't go to bed late."],
        ["She should skip breakfast.", "she shouldn't skip breakfast."],
        ["Make inability: I could go out yesterday.", "i couldn't go out yesterday."],
        ["He could swim at 3.", "he couldn't swim at 3."],
        ["She could open the jar.", "she couldn't open the jar."],
        ["They could run fast.", "they couldn't run fast."],
        ["We could finish the test.", "we couldn't finish the test."],
      ],
      tr: [
        ["Тебе следует пить воду.", "you should drink water."],
        ["Тебе не следует есть много сладкого.", "you shouldn't eat too many sweets."],
        ["Он умел плавать в 6 лет.", "he could swim when he was 6."],
        ["Она умела читать в 5 лет.", "she could read at 5."],
        ["Я не мог выйти вчера.", "i couldn't go out yesterday."],
        ["Нам следует быть тихими в классе.", "we should be quiet in class."],
        ["Они могли быстро бегать.", "they could run fast."],
        ["Тебе нельзя быть грубым.", "you shouldn't be rude."],
        ["Он умел играть на пианино.", "he could play the piano."],
        ["Она не могла открыть дверь.", "she couldn't open the door."],
      ],
    });

    add(13, "Object pronouns + who/which", "Object pronouns: me/you/him/her/it/us/them. who = people, which = things.", "Объектные: me/you/him/her/it/us/them. who — люди, which — вещи.", {
      fill: [
        ["Give it to ____. (I)", "me"],
        ["I see ____. (he)", "him"],
        ["She helps ____. (we)", "us"],
        ["They call ____. (she)", "her"],
        ["I like ____. (they)", "them"],
        ["Take ____. (it)", "it"],
        ["He knows ____. (you)", "you"],
        ["We visit ____. (they)", "them"],
        ["Tell ____. (he)", "him"],
        ["Help ____. (I)", "me"],
      ],
      choose: [
        ["Choose: I like (he/him).", "him"],
        ["Choose: She calls (we/us).", "us"],
        ["Choose: Give it to (I/me).", "me"],
        ["Choose: They see (she/her).", "her"],
        ["Choose: He knows (they/them).", "them"],
        ["Choose: This is the boy (who/which) lives here.", "who"],
        ["Choose: This is the book (who/which) I like.", "which"],
        ["Choose: The girl (who/which) is my friend.", "who"],
        ["Choose: The bag (who/which) is red.", "which"],
        ["Choose: The people (who/which) help us.", "who"],
      ],
      qs: [
        ["Make a question: (you / help / me?)", "do you help me?"],
        ["(she / call / him?)", "does she call him?"],
        ["(they / see / her?)", "do they see her?"],
        ["(he / know / them?)", "does he know them?"],
        ["(we / visit / you?)", "do we visit you?"],
        ["Make: who/which: The boy ____ runs fast. (who)", "the boy who runs fast."],
        ["The book ____ i like. (which)", "the book which i like."],
        ["The girl ____ is my friend. (who)", "the girl who is my friend."],
        ["The bag ____ is red. (which)", "the bag which is red."],
        ["The people ____ help us. (who)", "the people who help us."],
      ],
      neg: [
        ["Make negative: I like him.", "i don't like him."],
        ["She calls us.", "she doesn't call us."],
        ["They see her.", "they don't see her."],
        ["He knows them.", "he doesn't know them."],
        ["We visit you.", "we don't visit you."],
        ["Give it to me.", "don't give it to me."],
        ["Help him.", "don't help him."],
        ["Call her.", "don't call her."],
        ["Take it.", "don't take it."],
        ["Tell them.", "don't tell them."],
      ],
      tr: [
        ["Дай это мне.", "give it to me."],
        ["Я вижу его.", "i see him."],
        ["Она помогает нам.", "she helps us."],
        ["Они звонят ей.", "they call her."],
        ["Я люблю их.", "i like them."],
        ["Это мальчик, который здесь живёт.", "this is the boy who lives here."],
        ["Это книга, которую я люблю.", "this is the book which i like."],
        ["Это девочка, которая моя подруга.", "this is the girl who is my friend."],
        ["Это сумка, которая красная.", "this is the bag which is red."],
        ["Это люди, которые помогают нам.", "these are the people who help us."],
      ],
    });

    add(14, "Past Continuous + on/in", "Past Continuous: was/were + V-ing (in progress). on = days/dates; in = months/years.", "Past Continuous: was/were + ing. on — дни/даты, in — месяцы/годы.", {
      fill: [
        ["I ____ (watch) TV at 7 pm. (was/were)", "was watching"],
        ["They ____ (play) at 5 pm.", "were playing"],
        ["She ____ (read) at 8 pm.", "was reading"],
        ["We ____ (do) homework at 6 pm.", "were doing"],
        ["He ____ (sleep) at 9 pm.", "was sleeping"],
        ["On / In: ____ Monday", "on"],
        ["On / In: ____ April", "in"],
        ["On / In: ____ 2025", "in"],
        ["On / In: ____ 14 December", "on"],
        ["On / In: ____ summer", "in"],
      ],
      choose: [
        ["Choose: I (was/were) watching.", "was"],
        ["Choose: They (was/were) playing.", "were"],
        ["Choose: She (was/were) reading.", "was"],
        ["Choose: We (was/were) doing.", "were"],
        ["Choose: He (was/were) sleeping.", "was"],
        ["Choose: (on/in) Monday", "on"],
        ["Choose: (on/in) April", "in"],
        ["Choose: (on/in) 2024", "in"],
        ["Choose: (on/in) 12 May", "on"],
        ["Choose: (on/in) winter", "in"],
      ],
      qs: [
        ["(you / watch / TV at 7?)", "were you watching tv at 7?"],
        ["(they / play at 5?)", "were they playing at 5?"],
        ["(she / read at 8?)", "was she reading at 8?"],
        ["(we / do homework at 6?)", "were we doing homework at 6?"],
        ["(he / sleep at 9?)", "was he sleeping at 9?"],
        ["Make: on/in: My birthday is ____ May.", "my birthday is in may."],
        ["My birthday is ____ 12 May.", "my birthday is on 12 may."],
        ["School starts ____ September.", "school starts in september."],
        ["The lesson is ____ Monday.", "the lesson is on monday."],
        ["We meet ____ 2025.", "we meet in 2025."],
      ],
      neg: [
        ["I was watching TV.", "i wasn't watching tv."],
        ["They were playing.", "they weren't playing."],
        ["She was reading.", "she wasn't reading."],
        ["We were doing homework.", "we weren't doing homework."],
        ["He was sleeping.", "he wasn't sleeping."],
        ["My birthday is in May. (negative)", "my birthday isn't in may."],
        ["The lesson is on Monday. (negative)", "the lesson isn't on monday."],
        ["School starts in September. (negative)", "school doesn't start in september."],
        ["We meet in 2025. (negative)", "we don't meet in 2025."],
        ["My birthday is on 12 May. (negative)", "my birthday isn't on 12 may."],
      ],
      tr: [
        ["Я смотрел ТВ в 7 вечера.", "i was watching tv at 7 pm."],
        ["Они играли в 5 часов.", "they were playing at 5 pm."],
        ["Она читала в 8.", "she was reading at 8 pm."],
        ["Мы делали домашку в 6.", "we were doing homework at 6 pm."],
        ["Он спал в 9.", "he was sleeping at 9 pm."],
        ["В понедельник.", "on monday"],
        ["В апреле.", "in april"],
        ["В 2025 году.", "in 2025"],
        ["14 декабря.", "on 14 december"],
        ["Летом.", "in summer"],
      ],
    });

    add(15, "Past Simple vs Past Continuous", "Past Simple = finished; Past Continuous = in progress (when… happened).", "Past Simple — завершено; Past Continuous — процесс (когда… произошло).", {
      fill: [
        ["I ____ (walk) when I ____ (see) him.", "was walking; saw"],
        ["She ____ (read) when the phone ____ (ring).", "was reading; rang"],
        ["They ____ (play) when it ____ (start) to rain.", "were playing; started"],
        ["We ____ (do) homework when mum ____ (come) home.", "were doing; came"],
        ["He ____ (sleep) when I ____ (open) the door.", "was sleeping; opened"],
        ["Choose: I (watched/was watching) TV at 7.", "was watching"],
        ["Choose: Yesterday I (watched/was watching) TV.", "watched"],
        ["Choose: She (fell/was falling) and hurt her leg.", "fell"],
        ["Choose: We (ran/were running) when we met him.", "were running"],
        ["Choose: They (played/were playing) yesterday.", "played"],
      ],
      choose: [
        ["Choose: I (was walking / walked) when I saw him.", "was walking"],
        ["Choose: She (read / was reading) when it rang.", "was reading"],
        ["Choose: They (played / were playing) when it started.", "were playing"],
        ["Choose: We (did / were doing) homework when mum came.", "were doing"],
        ["Choose: He (slept / was sleeping) when I opened the door.", "was sleeping"],
        ["Choose: Past Simple (finished) = (did / was doing)", "did"],
        ["Choose: Past Continuous (process) = (did / was doing)", "was doing"],
        ["Choose: The phone (rang / was ringing) suddenly.", "rang"],
        ["Choose: I (fell / was falling) and broke it.", "fell"],
        ["Choose: We (were running / ran) at 6 pm.", "were running"],
      ],
      qs: [
        ["(you / walk / when you saw him?)", "were you walking when you saw him?"],
        ["(she / read / when it rang?)", "was she reading when it rang?"],
        ["(they / play / when it started?)", "were they playing when it started?"],
        ["(we / do homework / when mum came?)", "were we doing homework when mum came?"],
        ["(he / sleep / when you opened the door?)", "was he sleeping when you opened the door?"],
        ["(what / you / do / at 7 pm?)", "what were you doing at 7 pm?"],
        ["(what / happened / yesterday?)", "what happened yesterday?"],
        ["(did / the phone / ring?)", "did the phone ring?"],
        ["(were / they / running / at 6?)", "were they running at 6?"],
        ["(did / you / fall?)", "did you fall?"],
      ],
      neg: [
        ["I was walking when I saw him. (neg)", "i wasn't walking when i saw him."],
        ["She was reading when it rang. (neg)", "she wasn't reading when it rang."],
        ["They were playing when it started. (neg)", "they weren't playing when it started."],
        ["We were doing homework when mum came. (neg)", "we weren't doing homework when mum came."],
        ["He was sleeping when I opened the door. (neg)", "he wasn't sleeping when i opened the door."],
        ["Yesterday I watched TV. (neg)", "yesterday i didn't watch tv."],
        ["The phone rang. (neg)", "the phone didn't ring."],
        ["I fell. (neg)", "i didn't fall."],
        ["We ran. (neg)", "we didn't run."],
        ["They played yesterday. (neg)", "they didn't play yesterday."],
      ],
      tr: [
        ["Я шёл, когда увидел его.", "i was walking when i saw him."],
        ["Она читала, когда зазвонил телефон.", "she was reading when the phone rang."],
        ["Они играли, когда начался дождь.", "they were playing when it started to rain."],
        ["Мы делали домашку, когда мама пришла.", "we were doing homework when mum came home."],
        ["Он спал, когда я открыл дверь.", "he was sleeping when i opened the door."],
        ["В 7 вечера я смотрел ТВ.", "at 7 pm i was watching tv."],
        ["Вчера я смотрел ТВ.", "yesterday i watched tv."],
        ["Я упал и ушиб ногу.", "i fell and hurt my leg."],
        ["Мы бежали, когда встретили его.", "we were running when we met him."],
        ["Они играли вчера.", "they played yesterday."],
      ],
    });
  }

  addUnit10to15();

// ===== TESTS 1–15 (10 questions each) =====
const TESTS_1_15 = [
  {
    id: "t1",
    title: "Test 1 — Unit 1 (Present Simple vs Present Continuous)",
    items: [
      { id: "t1q1", prompt: "He ___ (play) football every day.", answer: "plays" },
      { id: "t1q2", prompt: "She ___ (watch) TV now.", answer: "is watching" },
      { id: "t1q3", prompt: "They ___ (go) to school on Mondays.", answer: "go" },
      { id: "t1q4", prompt: "I ___ (read) a book at the moment.", answer: "am reading" },
      { id: "t1q5", prompt: "We ___ (not / like) milk.", answer: "don't like" },
      { id: "t1q6", prompt: "He ___ (not / go) to bed late.", answer: "doesn't go" },
      { id: "t1q7", prompt: "___ she ___ (do) her homework every day? (Do/Does)", answer: "does she do" },
      { id: "t1q8", prompt: "___ you ___ (listen) to music now? (Are/Do)", answer: "are you listening" },
      { id: "t1q9", prompt: "My dad ___ (work) in a bank.", answer: "works" },
      { id: "t1q10", prompt: "Cats ___ (sleep) a lot.", answer: "sleep" },
    ],
  },

  {
    id: "t2",
    title: "Test 2 — Unit 2 (Past Simple: regular + be)",
    items: [
      { id: "t2q1", prompt: "Yesterday I ___ (visit) my grandma.", answer: "visited" },
      { id: "t2q2", prompt: "We ___ (watch) a film last night.", answer: "watched" },
      { id: "t2q3", prompt: "She ___ (not / play) tennis yesterday.", answer: "didn't play" },
      { id: "t2q4", prompt: "___ you ___ (clean) your room? (Did)", answer: "did you clean" },
      { id: "t2q5", prompt: "He ___ (be) at home вчера. (was/were)", answer: "was" },
      { id: "t2q6", prompt: "They ___ (be) happy yesterday.", answer: "were" },
      { id: "t2q7", prompt: "It ___ (not / be) cold yesterday.", answer: "wasn't" },
      { id: "t2q8", prompt: "___ she at school yesterday? (Was/Were)", answer: "was she" },
      { id: "t2q9", prompt: "I ___ (finish) my homework an hour ago.", answer: "finished" },
      { id: "t2q10", prompt: "We ___ (not / watch) TV last Sunday.", answer: "didn't watch" },
    ],
  },

  {
    id: "t3",
    title: "Test 3 — Unit 3 (Past Simple: irregular verbs)",
    items: [
      { id: "t3q1", prompt: "I ___ (go) to the park yesterday.", answer: "went" },
      { id: "t3q2", prompt: "She ___ (have) a sandwich for lunch.", answer: "had" },
      { id: "t3q3", prompt: "They ___ (see) a dog in the street.", answer: "saw" },
      { id: "t3q4", prompt: "We ___ (buy) a new book.", answer: "bought" },
      { id: "t3q5", prompt: "He ___ (not / go) to school yesterday.", answer: "didn't go" },
      { id: "t3q6", prompt: "___ you ___ (do) your homework? (Did)", answer: "did you do" },
      { id: "t3q7", prompt: "I ___ (not / have) time last night.", answer: "didn't have" },
      { id: "t3q8", prompt: "She ___ (make) a cake.", answer: "made" },
      { id: "t3q9", prompt: "They ___ (take) the bus.", answer: "took" },
      { id: "t3q10", prompt: "We ___ (not / see) him вчера.", answer: "didn't see" },
    ],
  },

  {
    id: "t4",
    title: "Test 4 — Unit 4 (Possessive pronouns + 's)",
    items: [
      { id: "t4q1", prompt: "This is my bag. It is ___. (mine/yours)", answer: "mine" },
      { id: "t4q2", prompt: "That is her book. It is ___.", answer: "hers" },
      { id: "t4q3", prompt: "These are our bikes. They are ___.", answer: "ours" },
      { id: "t4q4", prompt: "Those are their shoes. They are ___.", answer: "theirs" },
      { id: "t4q5", prompt: "This is your pen. It is ___.", answer: "yours" },
      { id: "t4q6", prompt: "Tom has a dog. It is ___ dog. (Tom’s)", answer: "Tom's" },
      { id: "t4q7", prompt: "The girls have a room. It is the ___ room. (girls’)", answer: "girls'" },
      { id: "t4q8", prompt: "My dad has a car. It is my ___ car. (dad’s)", answer: "dad's" },
      { id: "t4q9", prompt: "This is Ali’s hat. The hat is ___. (his)", answer: "his" },
      { id: "t4q10", prompt: "This is Sara’s dress. The dress is ___.", answer: "hers" },
    ],
  },

  {
    id: "t5",
    title: "Test 5 — Unit 5 (Have to / must + Imperative)",
    items: [
      { id: "t5q1", prompt: "I ___ wear a uniform at school. (have to)", answer: "have to" },
      { id: "t5q2", prompt: "He ___ do his homework. (has to)", answer: "has to" },
      { id: "t5q3", prompt: "We ___ run in the corridor. (mustn't)", answer: "mustn't" },
      { id: "t5q4", prompt: "You ___ be quiet in the library. (must)", answer: "must" },
      { id: "t5q5", prompt: "Yesterday I ___ go to the doctor. (had to)", answer: "had to" },
      { id: "t5q6", prompt: "Imperative: ___ the door, please. (open)", answer: "open" },
      { id: "t5q7", prompt: "Negative imperative: ___ touch it!", answer: "don't" },
      { id: "t5q8", prompt: "She ___ tidy her room every day. (has to)", answer: "has to" },
      { id: "t5q9", prompt: "We ___ eat in class. (mustn't)", answer: "mustn't" },
      { id: "t5q10", prompt: "You ___ listen to your teacher. (must)", answer: "must" },
    ],
  },

  {
    id: "t6",
    title: "Test 6 — Unit 6 (Comparatives & Superlatives)",
    items: [
      { id: "t6q1", prompt: "A lion is ___ than a cat. (big)", answer: "bigger" },
      { id: "t6q2", prompt: "This book is ___ than that one. (interesting)", answer: "more interesting" },
      { id: "t6q3", prompt: "My bag is ___ than your bag. (heavy)", answer: "heavier" },
      { id: "t6q4", prompt: "She is the ___ student in the class. (smart)", answer: "smartest" },
      { id: "t6q5", prompt: "This is the ___ day of my life. (good)", answer: "best" },
      { id: "t6q6", prompt: "Winter is ___ than summer here. (cold)", answer: "colder" },
      { id: "t6q7", prompt: "He is the ___ runner. (fast)", answer: "fastest" },
      { id: "t6q8", prompt: "Math is ___ than history for me. (difficult)", answer: "more difficult" },
      { id: "t6q9", prompt: "This chair is the ___ (comfortable).", answer: "most comfortable" },
      { id: "t6q10", prompt: "Bad → ___ → worst.", answer: "worse" },
    ],
  },

  {
    id: "t7",
    title: "Test 7 — Unit 7 (will / won't)",
    items: [
      { id: "t7q1", prompt: "I ___ help you tomorrow. (will)", answer: "will" },
      { id: "t7q2", prompt: "She ___ be late. (won't)", answer: "won't" },
      { id: "t7q3", prompt: "___ you come to my party? (Will)", answer: "will" },
      { id: "t7q4", prompt: "They ___ travel next week. (will)", answer: "will" },
      { id: "t7q5", prompt: "He ___ forget your birthday. (won't)", answer: "won't" },
      { id: "t7q6", prompt: "Will she ___ (call) me later?", answer: "call" },
      { id: "t7q7", prompt: "I think it ___ rain soon.", answer: "will" },
      { id: "t7q8", prompt: "We ___ go to the cinema tonight.", answer: "will" },
      { id: "t7q9", prompt: "I ___ (not) eat that!", answer: "won't" },
      { id: "t7q10", prompt: "___ they win the game?", answer: "will" },
    ],
  },

  {
    id: "t8",
    title: "Test 8 — Unit 8 (much/many/some/any/a lot of)",
    items: [
      { id: "t8q1", prompt: "How ___ milk is there? (much/many)", answer: "much" },
      { id: "t8q2", prompt: "How ___ apples do you want? (much/many)", answer: "many" },
      { id: "t8q3", prompt: "I have ___ friends. (a lot of)", answer: "a lot of" },
      { id: "t8q4", prompt: "There isn't ___ bread. (any/some)", answer: "any" },
      { id: "t8q5", prompt: "Do you have ___ money? (any/some)", answer: "any" },
      { id: "t8q6", prompt: "I want ___ water, please. (some/any)", answer: "some" },
      { id: "t8q7", prompt: "We haven't got ___ eggs. (any)", answer: "any" },
      { id: "t8q8", prompt: "There are ___ students in the class. (many/much)", answer: "many" },
      { id: "t8q9", prompt: "I don't drink ___ coffee. (much)", answer: "much" },
      { id: "t8q10", prompt: "We've got ___ homework today. (a lot of)", answer: "a lot of" },
    ],
  },

  {
    id: "t9",
    title: "Test 9 — Unit 9 (to + infinitive: purpose)",
    items: [
      { id: "t9q1", prompt: "I went to the shop ___ buy bread. (to)", answer: "to" },
      { id: "t9q2", prompt: "She studied hard ___ pass the test.", answer: "to" },
      { id: "t9q3", prompt: "We use a pen ___ write.", answer: "to" },
      { id: "t9q4", prompt: "He called me ___ ask a question.", answer: "to" },
      { id: "t9q5", prompt: "They went to the park ___ play football.", answer: "to" },
      { id: "t9q6", prompt: "I need a chair ___ sit down.", answer: "to" },
      { id: "t9q7", prompt: "She opened the window ___ get fresh air.", answer: "to" },
      { id: "t9q8", prompt: "He went to the library ___ read.", answer: "to" },
      { id: "t9q9", prompt: "We turned on the TV ___ watch the news.", answer: "to" },
      { id: "t9q10", prompt: "I’m learning English ___ speak to people.", answer: "to" },
    ],
  },

  {
    id: "t10",
    title: "Test 10 — Unit 10 (Present Perfect: have/has + V3)",
    items: [
      { id: "t10q1", prompt: "I ___ (visit) London. (have/has)", answer: "have visited" },
      { id: "t10q2", prompt: "She ___ (see) this film.", answer: "has seen" },
      { id: "t10q3", prompt: "They ___ (not / finish) homework.", answer: "haven't finished" },
      { id: "t10q4", prompt: "He ___ (not / eat) yet.", answer: "hasn't eaten" },
      { id: "t10q5", prompt: "___ you ever ___ (be) to Astana?", answer: "have you ever been" },
      { id: "t10q6", prompt: "___ she ___ (do) her project?", answer: "has she done" },
      { id: "t10q7", prompt: "We ___ (make) a cake today.", answer: "have made" },
      { id: "t10q8", prompt: "My dad ___ (buy) a new phone.", answer: "has bought" },
      { id: "t10q9", prompt: "I ___ (not / see) him today.", answer: "haven't seen" },
      { id: "t10q10", prompt: "They ___ (play) this game before.", answer: "have played" },
    ],
  },

  {
    id: "t11",
    title: "Test 11 — Unit 11 (ever / never)",
    items: [
      { id: "t11q1", prompt: "Have you ___ ridden a horse? (ever/never)", answer: "ever" },
      { id: "t11q2", prompt: "I have ___ eaten sushi. (ever/never)", answer: "never" },
      { id: "t11q3", prompt: "Has she ___ been to the sea?", answer: "ever" },
      { id: "t11q4", prompt: "We have ___ seen a whale.", answer: "never" },
      { id: "t11q5", prompt: "Have they ___ tried ice skating?", answer: "ever" },
      { id: "t11q6", prompt: "He has ___ lost his keys. (ever/never)", answer: "never" },
      { id: "t11q7", prompt: "Have you ___ met a famous person?", answer: "ever" },
      { id: "t11q8", prompt: "I have ___ been to Japan.", answer: "never" },
      { id: "t11q9", prompt: "Has your friend ___ helped you?", answer: "ever" },
      { id: "t11q10", prompt: "She has ___ lied to me.", answer: "never" },
    ],
  },

  {
    id: "t12",
    title: "Test 12 — Unit 12 (should / shouldn't + could / couldn't)",
    items: [
      { id: "t12q1", prompt: "You ___ do your homework. (should)", answer: "should" },
      { id: "t12q2", prompt: "You ___ eat so much sugar. (shouldn't)", answer: "shouldn't" },
      { id: "t12q3", prompt: "I ___ swim when I was 5. (could/couldn't)", answer: "could" },
      { id: "t12q4", prompt: "He ___ ride a bike last year. (couldn't)", answer: "couldn't" },
      { id: "t12q5", prompt: "We ___ be polite.", answer: "should" },
      { id: "t12q6", prompt: "She ___ stay up late. (shouldn't)", answer: "shouldn't" },
      { id: "t12q7", prompt: "They ___ speak English when they were young. (could)", answer: "could" },
      { id: "t12q8", prompt: "I ___ open the door — it was locked. (couldn't)", answer: "couldn't" },
      { id: "t12q9", prompt: "You ___ drink water. (should)", answer: "should" },
      { id: "t12q10", prompt: "You ___ shout in class. (shouldn't)", answer: "shouldn't" },
    ],
  },

  {
    id: "t13",
    title: "Test 13 — Unit 13 (Object pronouns + who/which)",
    items: [
      { id: "t13q1", prompt: "I see Tom. I see ___. (him)", answer: "him" },
      { id: "t13q2", prompt: "She likes Anna. She likes ___. (her)", answer: "her" },
      { id: "t13q3", prompt: "We know the boys. We know ___. (them)", answer: "them" },
      { id: "t13q4", prompt: "He helps me. He helps ___.", answer: "me" },
      { id: "t13q5", prompt: "This is the girl ___ lives next door. (who/which)", answer: "who" },
      { id: "t13q6", prompt: "This is the book ___ I like. (who/which)", answer: "which" },
      { id: "t13q7", prompt: "I call my friends. I call ___.", answer: "them" },
      { id: "t13q8", prompt: "They visit us. They visit ___.", answer: "us" },
      { id: "t13q9", prompt: "That’s the dog ___ can swim. (which)", answer: "which" },
      { id: "t13q10", prompt: "That’s the teacher ___ teaches English. (who)", answer: "who" },
    ],
  },

  {
    id: "t14",
    title: "Test 14 — Unit 14 (Past Continuous + on/in)",
    items: [
      { id: "t14q1", prompt: "At 7 pm I ___ (do) my homework. (was/were + -ing)", answer: "was doing" },
      { id: "t14q2", prompt: "They ___ (play) when it started to rain.", answer: "were playing" },
      { id: "t14q3", prompt: "She ___ (not / watch) TV at 9 pm.", answer: "wasn't watching" },
      { id: "t14q4", prompt: "___ he ___ (sleep) at 10 pm? (Was ... -ing)", answer: "was he sleeping" },
      { id: "t14q5", prompt: "We ___ (not / listen) to music.", answer: "weren't listening" },
      { id: "t14q6", prompt: "I was born ___ 2012. (in/on)", answer: "in" },
      { id: "t14q7", prompt: "My birthday is ___ May. (in/on)", answer: "in" },
      { id: "t14q8", prompt: "My birthday is ___ 10th May. (in/on)", answer: "on" },
      { id: "t14q9", prompt: "School starts ___ Monday. (in/on)", answer: "on" },
      { id: "t14q10", prompt: "At 6 o’clock we ___ (have) dinner.", answer: "were having" },
    ],
  },

  {
    id: "t15",
    title: "Test 15 — Unit 15 (Past Simple vs Past Continuous)",
    items: [
      { id: "t15q1", prompt: "I ___ (walk) home when I ___ (see) my friend.", answer: "was walking when I saw" },
      { id: "t15q2", prompt: "She ___ (do) homework at 8 pm yesterday.", answer: "was doing" },
      { id: "t15q3", prompt: "They ___ (play) football yesterday. (Past Simple)", answer: "played" },
      { id: "t15q4", prompt: "We ___ (watch) TV when the phone ___ (ring).", answer: "were watching when the phone rang" },
      { id: "t15q5", prompt: "He ___ (not / go) to school yesterday.", answer: "didn't go" },
      { id: "t15q6", prompt: "At 9 pm I ___ (sleep).", answer: "was sleeping" },
      { id: "t15q7", prompt: "I ___ (finish) my homework, then I ___ (play).", answer: "finished then I played" },
      { id: "t15q8", prompt: "They ___ (not / listen) when the teacher ___ (speak).", answer: "weren't listening when the teacher spoke" },
      { id: "t15q9", prompt: "He ___ (run) when he ___ (fall).", answer: "was running when he fell" },
      { id: "t15q10", prompt: "We ___ (go) home while it ___ (rain).", answer: "went home while it was raining" },
    ],
  },
];

window.APP_DATA = { units, tests: TESTS_1_15 };
})();
